# Generated by Django 4.2.7 on 2023-11-22 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0002_tarefa_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjetoInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_do_projeto', models.CharField(max_length=100)),
                ('descricao_do_projeto', models.TextField()),
            ],
        ),
    ]
