# Generated by Django 4.2.7 on 2023-11-22 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0003_projetoinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projetoinfo',
            old_name='descricao_do_projeto',
            new_name='descricao',
        ),
        migrations.RemoveField(
            model_name='projetoinfo',
            name='nome_do_projeto',
        ),
        migrations.AddField(
            model_name='projetoinfo',
            name='nome',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
